name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # https://hub.docker.com/r/fabernovel/android/tags
    container: fabernovel/android:api-33-gcloud-ndk-v1.7.0

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          /root/.gradle/caches
          /root/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Gradle build
      run: ./gradlew assembleDebug
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-apk
        path: app/build/outputs/apk/debug/app-debug.apk

  test-short: 
     runs-on: ubuntu-latest
     needs: build
     # https://hub.docker.com/r/fabernovel/android/tags
     container: fabernovel/android:api-33-gcloud-ndk-v1.7.0

     steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: Gradle cache
       uses: actions/cache@v3
       with:
         path: |
          /root/.gradle/caches
          /root/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
          ${{ runner.os }}-gradle-
     - name: Gradle build
       run: ./gradlew compileDebugUnitTestSources
       
  integration-tests: 
     runs-on: ubuntu-latest
     needs: build
     # forces a manual start of the build
     environment: emulator
     # https://hub.docker.com/r/fabernovel/android/tags
     container: fabernovel/android:api-33-gcloud-ndk-v1.7.0

     steps:
     - name: checkout
       uses: actions/checkout@v3
     - name: Gradle cache
       uses: actions/cache@v3
       with:
         path: |
          /root/.gradle/caches
          /root/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
          ${{ runner.os }}-gradle-
     - name: Gradle build
       run: ./gradlew compileDebugUnitTestSources       

  code-scan:
    runs-on: ubuntu-latest
    needs: [test-short, integration-tests]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup CodeQL
        uses: github/codeql-action/setup@v2
      - name: Build and Analyze
        run: |
          codeql database create --language=kotlin --source-root=. MyDB
          codeql analyze --database=MyDB --format=sarif-latest --output=results.sarif
    
    
  upload-and-sign:
      runs-on: ubuntu-latest
      environment: release
      needs: code-scan

      steps:
      - name: prepareUpload
        run: echo 'doing stuff'
      - name: upload
        run: echo 'doing stuff'
  
