name: "Android Feature Branch Pipeline"

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "feature/**" ]

jobs:

  build:
    runs-on: ubuntu-latest
    # https://hub.docker.com/r/fabernovel/android/tags
    container: fabernovel/android:api-33-gcloud-ndk-v1.7.0

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Gradle cache
      uses: actions/cache@v3
      with:
        path: |
          /root/.gradle/caches
          /root/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Gradle build
      run: ./gradlew assembleDebug
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
    
  secureCodeScanning:
    name: NowSecure
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run NowSecure
        uses: nowsecure/nowsecure-action@3b439db31b6dce857b09f5222fd13ffc3159ad26
        with:
          token: ${{ secrets.NS_TOKEN }}
          app_file: app-debug.apk                 # Update this to a path to your .ipa or .apk
          group_id: com.example.testapplication                 # Update this to your desired Platform group ID

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: NowSecure.sarif
  
  
